### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hroncok** [lopatovsky/Maze#3]
I can block all path to the castle and your dudes yous go crazy (for example they go out of the maze).

![video](https://cloud.githubusercontent.com/assets/2401856/21578198/75d85af0-cf77-11e6-969c-55f8d037cf8b.gif)

**Comment by lopatovsky** [comment]
It shouldn't be able to build the last of the walls in that case, it is the bug I haven't encountered before. I will look at it.

**Comment by lopatovsky** [comment]
It is fixed now,  there was a mistake in array indexing.  Please update to the last commit.
https://github.com/lopatovsky/Maze/commit/dd18c3591d888fdb3ad59a78f477b1da0fe8bac2
